name: ✨ Feature Request
description: Suggest a new feature or improvement.
title: "[FEATURE] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical