name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md